name: HUBER Motion Lab
favicon: null
layout_spectrum: 0.5827559661120176
typography_spectrum: 0.6538543598726392
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.7645638843532652
  lightness: 0.9302546286489815
  saturation: 0.7093470352701843
  rhythmicContrast: 0.9438100624829531
purpose: []
